name: Remote Dispatch Action Responder

on: 
  repository_dispatch:
    types: [e2e]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Get Specfic Release
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: | 
          echo ${{ github.event.client_payload  }}