name: Remote Dispatch Action Responder

on: 
  repository_dispatch:
    types: [e2e]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Get Specfic Release
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: | 
          echo ${{ github.event.client_payload.PR  }}
          echo ${{ github.event.client_payload.repo  }}

          export PR_SHA=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/Fouz/coffee-shop/pulls/${{ github.event.client_payload.PR  }}/commits | jq -r '.[0].sha' )
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Fouz/coffee-shop/statuses/${PR_SHA} -d '{"state":"success", "context": "run", "description": "Skipped for deployment PR."}'