name: Remote Dispatch Action Responder

on: 
  # push:
  #   branches:
  #     - master
  repository_dispatch:
    types: [e2e]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # - name: check
      #   run: |
      #     echo ${{ github.event.client_payload.number  }}
      #     echo ${{ github.event.client_payload.PR  }}
      #     echo ${{ github.event.client_payload.REPO  }}
      - name: Test app
        continue-on-error: ${{  github.event_name == 'repository_dispatch'  }}
        id: test-app 
        run: |
          exit 1
          # echo "Testing app (randomly fails)"
          # if [[ $(($RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi

      - name: test-clean
        if: ${{  github.event_name == 'repository_dispatch'  }}
        run: |
          export PR_SHA=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token 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" https://api.github.com/repos/Fouz/coffee-shop/pulls/${{ github.event.client_payload.PR }}/commits | jq -r '.[0].sha' )
          if ${{steps.test-app.outcome != 'success'}}
          then
          curl -X POST -H "Authorization: token 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" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Fouz/coffee-shop/statuses/$PR_SHA -d '{"state":"error", "context": "e2e test", "description": "e2e test failed"}'
          else
          curl -X POST -H "Authorization: token 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" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Fouz/coffee-shop/statuses/$PR_SHA -d '{"state":"success", "context": "e2e test", "description": "e2e test failed"}'
          fi